### ISSUE TITLE
metric values

### ISSUE THREAD

**Issue by riogrande75** [bellrichm/weewx-mqttpublish#10]
Just installed this plugin as it's the only mqtt extension that works out of the box with weewx 5.1.0.
Unfortunately almost all values are in imperial system (e.g. inTemp_F) but I need it metric (inTemp_C).
I've changed **[StdConvert] -> target_unit = METRICWX** in weewx.conf and reconfigured database, but no change in mqtt output.

Any chance to get this configurable?

**Comment by bellrichm** [comment]
For the topic(s) being published, try setting `unit_system = METRICWX`. For example
```
.
.
.
[[[Topics]]]
    [[[[topic being published to]]]]
        unit_system = METRICWX
```

Disclaimer, with other extensions supporting mqtt publishing, this repository gets limited support. You will notice that by the lack of documentation. It also does not have a test suite, so unless it code that I run it will have been limited testing. This is one section of code that I do not use. Let me know how it goes. If it doesn’t work for you, I will look at it more closely
rich

**Comment by riogrande75** [comment]
Yup, that did the trick.
THX for your quick reply!

**Comment by bellrichm** [comment]
Thanks for letting me know!
